spring:
  application:
    name: CatalogGateway
  profiles:
    active: dev

  data:
    mongodb:
      uri: mongodb://localhost:27017/catalog_db
    redis:
      host: localhost
      port: 6379

api:
  security:
    token:
      secret: ${JWT_SECRET}

external:
  viacep:
    url: https://viacep.com.br/ws

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

catalog:
  admin:
    seed:
      email: ${ADMIN_SEED_EMAIL}
      password: ${ADMIN_SEED_PASSWORD}
      name: ${ADMIN_SEED_NAME}

  rate-limit:
    enabled: true
    anonymous:
      capacity: 30
      refill-tokens: 30
      refill-period-seconds: 60
    auth-endpoints:
      capacity: 5
      refill-tokens: 5
      refill-period-seconds: 60
    customer:
      capacity: 60
      refill-tokens: 60
      refill-period-seconds: 60
    manager:
      capacity: 120
      refill-tokens: 120
      refill-period-seconds: 60
    admin:
      capacity: 300
      refill-tokens: 300
      refill-period-seconds: 60